source 'http://rubygems.org'

gem 'rails', '~> 3.0.1'
gem 'sqlite3-ruby', :require => 'sqlite3'

group :test do
  gem 'rspec-rails', '~> 2.1.0'
  gem 'factory_girl_rails'
  gem 'steak', '>= 1.0.0.rc.2'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'launchy'
end
